# Generated by Django 3.1.6 on 2021-03-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_auto_20210311_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(db_table='task_types', related_name='tasks', to='issue_tracker.Type'),
        ),
        migrations.AlterModelTable(
            name='task',
            table='tasks',
        ),
    ]
