# Generated by Django 3.1.6 on 2021-03-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20210314_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='issue_tracker.status', verbose_name='Статус'),
        ),
    ]
