# Generated by Django 3.1.6 on 2021-03-17 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0006_auto_20210317_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name_of_status',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=3000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name_of_type',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Тип'),
        ),
    ]
